apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: hackathon-auth
data:
  DB_HOST: "postgres-postgresql.hackathon-db.svc.cluster.local"
  DB_USER: "admin"
  REDIS_HOST: "redis-master.hackathon-redis.svc.cluster.local"
