apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: hackathon-auth
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: hackathon-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: auth-secret # Nome do Secret do K8s criado pelo ESO
    creationPolicy: Owner
  data:
    # Senha do banco de dados RDS PostgreSQL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "rds!db-051612da-a9be-4c36-a343-f9261a18f529-lrkPVU"
        property: password
    # Chave secreta do JWT (assinatura de tokens)
    - secretKey: JWT_SECRET
      remoteRef:
        key: "fiapx/jwt-secret"
        property: secret_key
    # Senha do Redis ElastiCache
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: "/fiapx-redis/redis/user_password-v4"
        property: password

        
